defaults:
  - dataset: rps
  - model: pn
train:
  batch_size: 32
  num_workers: 0
  val_shuffle: False # Whether to shuffle the valid and test dataloader
  n_epochs: 100
  gpus: '0' # This should be a string
resume_path: null
resume_version: null
resume_id: null
weights_path: null
debug: False
project: "vlr_proj"
exp_suffix: "exp"
exp_name: ???